### ISSUE TITLE
Bug: uses random model (?) if 4x rather than 2x specified

### ISSUE THREAD

**Issue by gwern** [Yukariin/SAN_pytorch#2]
If one uses `test.py` to upscale and uses any scale but `--scale 2` (eg `--scale 4`), instead of doing 2 upscales as requested (which would be much faster than running `test.py` twice), it instead prints out an odd message and appears to use some sort of randomly-initialized model instead of the specified model? At least, that's what the code seems to imply, and the generated upscale is barely recognizable.

Since the user has specified a model, it should either do a 4x upscale as requested or it should error out; it should not generate an image which is really bad.

**Comment by yukariin** [comment]
You're trying to use x2 model for x4 upscale. Probably one of pre-trained models from the readme.
Such behavior allowed for transfer training. Due to model architecture you don't actually need to train the whole model from scratch but only upsampler module, which is much faster. So you can use x2 model to train x3/x4/x8 model.
If you want to use x2 model to do a x4 upscale you need either to modify `test.py` to do two x2 passes, or use it to train x4 model by yourself.

**Comment by yukariin** [comment]
Also I'd recommend to use x1 N1 pass + xN N0 passes if you prefer to use x2 models instead of training a proper x4 model.
The first N1 pass will remove JPEG noise and create base image, while the further N0 passes will generate higher quality images.

**Comment by gwern** [comment]
Allowing retraining is good, of course, but it makes no sense to do that as part of the basic user script, especially when trying to run `--scale 4` does not train a model in the first place. [Another user](https://www.reddit.com/r/AnimeResearch/comments/gzsl12/san_a_new_anime_superresolution_upscaler_in/ftko42j/) has already been bitten by this.

If there's a better way to do 4x by a specific complex combination of models, that's another argument for implementing a 4x functionality instead of somehow expecting the user to do all this when they just want to upscale an image.

**Comment by yukariin** [comment]
That's not part of the user script, that's part of the model's `load_state_dict` (standard pytorch method to load stored models) which is used by user script. It's hard to implement sanity check of loading state dict so I'm going to add a note in the readme.
Also I'm planning to add x4 N0/N1 pre-trained models too.

**Comment by yukariin** [comment]
Okay, found a simple solution.
Added `transfer=False` to `load_state_dict`, default behavior is now similar to vanilla `load_state_dict` and throws `RuntimeError` when loading x2 state dict into non-x2 model.
