### ISSUE TITLE
Feature request: batching

### ISSUE THREAD

**Issue by gwern** [Yukariin/SAN_pytorch#3]
We've [been interested in a better anime upscaler](https://github.com/tensorfork/tensorfork/issues/25) for processing datasets for our Tensorfork work (eg my [face/figure/hand crops](https://www.gwern.net/Crops) extracted from [Danbooru2019](https://www.gwern.net/Danbooru2019)), since we use waifu2x to upscale images to meet our minimum 512px image size. Waifu2x is increasingly out of date and could bitrot at any time. I've taken a look at this SAN model with 4x and 8x upscale comparisons:

1. https://imgur.com/a/q0fFYtv
2. https://imgur.com/a/vuJhVVY

While SAN is much slower, it seems like the quality is indeed probably better for our usecase, and I appreciate that it's in PyTorch and you seem to be interested in maintaining it rather than it being abandonware.

The main drawback to using `test.py` right now is that it does an image at a time, not in-place. This means it would be absurdly slow to run on a Danbooru2019-scale dataset, as it would have to load the model onto GPU for every single image, unload, etc, and you wouldn't get anywhere close to 100% utilization, in part because you would have to avoid running too many SANs in parallel to avoid crashing each other by VRAM OOMs...

So it would be very useful if the script could be extended to take, say, a filelist or a directory glob, and do images in batches on GPU in a single run, and update the images in-place.

**Comment by yukariin** [comment]
It's pretty easy to implement a file list/dir glob handling.
Not sure about patch batching tho. Current ImageSplitter implementation generates two type of patches: one is exactly 48x48 patches which can be batched easily, and second is arbitrary size patches smaller or equal to 48 (e.g. 12x48, 48x20, 34x40) from the image edges.
I see two ways to solve this issue: modify ImageSplitter to pad input image to fit multiply of 48, or making a batch of 48x48 patches and run arbitrary size patches in single-batch-mode.

**Comment by yukariin** [comment]
Dir glob handling added in 5d362af

**Comment by gwern** [comment]
I would go with padding. It makes the code more straightforward and less buggy, and GPUs hate varying-size inputs so it's not like you necessarily lose that much performance.

**Comment by yukariin** [comment]
Patch batching added in 1e67300
ImageSplitter is now pads the input image to fit multiply of 48.  Added `--batch_size` option to `test.py` with default value `1`.
